backend:
  name: github
  repo: BrunoBusnardo/historia-tremembe
  branch: main

media_folder: "conteudo/imagens"
public_folder: "/conteudo/imagens"

collections:
  - name: "artigos"
    label: "Publicações e Artigos"
    folder: "conteudo/artigos"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Autor / Instituição", name: "author", widget: "string"}
      - {label: "Capa ou Imagem", name: "image", widget: "image", required: false}
      - {label: "Arquivo PDF", name: "pdffile", widget: "file", required: false}
      - {label: "Resumo / Texto", name: "body", widget: "markdown"}

  - name: "acervo"
    label: "Acervo Digital"
    folder: "conteudo/acervo"
    create: true
    fields:
      - {label: "Título do Item", name: "title", widget: "string"}
      - {label: "Tipo", name: "tipo", widget: "select", options: ["Fotografia", "Documento Textual", "Mapa/Planta"]}
      - {label: "Ano / Século", name: "periodo", widget: "string"}
      - {label: "Imagem / Documento", name: "image", widget: "image"}
      - {label: "Descrição", name: "description", widget: "text"}

  - name: "pedagogo"
    label: "Espaço do Professor"
    folder: "conteudo/pedagogo"
    create: true
    fields:
      - {label: "Título da Atividade", name: "title", widget: "string"}
      - {label: "Nível de Ensino", name: "nivel", widget: "string"}
      - {label: "Arquivo do Plano (PDF)", name: "pdffile", widget: "file"}
      - {label: "Descrição do Material", name: "body", widget: "markdown"}
